import { Slider, GroupBox, HorizontalBox, VerticalBox, GridBox } from "std-widgets.slint";

export component App inherits Window {
    in property <image> texture <=> image.source;
    out property <int> requested-texture-width: image.width/1phx;
    out property <int> requested-texture-height: image.height/1phx;

    preferred-width: 500px;
    preferred-height: 600px;
    title: "Slint OpenGL DMA-BUF Example";

    VerticalBox {
        Text {
            text: "This text is rendered using Slint. The rotating cube below is rendered into an OpenGL texture.";
            wrap: word-wrap;
        }

        image := Image {
            preferred-width: 640px;
            preferred-height: 640px;
            min-width: 64px;
            min-height: 64px;
            width: 100%;
            //height: 100%;
        }
    }
}
